version: "3.3"

networks:
  laravel:

services:
  php:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/code
    networks:
      - laravel

  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - "8053:80"
    volumes:
      - ./backend:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  mysql:
    image: mysql:5.7.35
    ports: 
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: tes_deptech
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  frontend:
    image: node:12.2.0-alpine
    working_dir: /app
    ports: 
      - 3053:8080
    volumes:
    - ./frontend:/app
    environment:
      - BACKEND_URL=http://localhost:8053/
    command: "npm run serve"
